-- Create bookings table
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT REFERENCES properties(id),
    
    start_date DATE,
    end_date DATE,
    guests INT,
    
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    customer_phone TEXT,
    message TEXT,
    
    status TEXT DEFAULT 'pending', -- pending, confirmed, cancelled
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Policy: Service role can do everything. Public can INSERT only.
CREATE POLICY "Anyone can create a booking" 
ON bookings FOR INSERT 
WITH CHECK (true);

-- Policy: Only service role can view bookings (or dashboard admins)
CREATE POLICY "Service role views all" 
ON bookings FOR SELECT 
USING (auth.role() = 'service_role');
