-- FIX DEFINITIVO E COMPLETO PER DB SUPABASE
-- Questo script controlla e crea TUTTE le tabelle e colonne necessarie, una per una.
-- Eseguilo tutto in una volta.

BEGIN;

-- 1. TABELLA BOOKINGS
CREATE TABLE IF NOT EXISTS public.bookings (
    id bigint generated by default as identity primary key
);

-- Aggiunta colonne una per una (Idempotente)
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS property_id bigint references public.properties(id);
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS user_email text; -- Correzione errore "user_email does not exist"
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS user_id uuid references auth.users(id);
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS start_date date;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS end_date date;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS total_price decimal(10, 2) default 0;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS status text default 'pending';
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS extra_services jsonb default '[]'::jsonb;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS created_at timestamp with time zone default timezone('utc'::text, now());

-- Constraint check su status (se non esiste va gestito diversamente, ma per ora droppiamo e ricreiamo il check se serve, o ci fidiamo del default)
-- Per sicurezza sui constraint:
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'bookings_status_check') THEN
        ALTER TABLE public.bookings ADD CONSTRAINT bookings_status_check CHECK (status IN ('pending', 'confirmed', 'paid', 'cancelled'));
    END IF;
END $$;


-- 2. TABELLA PROPERTIES (Assicuriamo le colonne JSON)
CREATE TABLE IF NOT EXISTS public.properties (
    id bigint primary key -- ID esistenti importati
);
ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS price decimal(10, 2);
ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS city text;
ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS address text;
ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS lat double precision;
ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS lng double precision;
ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS specs jsonb default '{}'::jsonb;
ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS features jsonb default '[]'::jsonb;
ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS images jsonb default '[]'::jsonb;
ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS extra_options jsonb default '[]'::jsonb;
ALTER TABLE public.properties ADD COLUMN IF NOT EXISTS image_url text;


-- 3. TABELLA PROFILES
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid references auth.users on delete cascade not null primary key
);
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role text default 'user';

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'profiles_role_check') THEN
        ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK (role IN ('user', 'admin'));
    END IF;
END $$;

-- 4. POLICIES (Sicurezza)
-- Abilitazione RLS
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Reset Policies Bookings
DROP POLICY IF EXISTS "Anyone can create a booking" ON public.bookings;
CREATE POLICY "Anyone can create a booking" ON public.bookings FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Users can view own bookings" ON public.bookings;
CREATE POLICY "Users can view own bookings" ON public.bookings FOR SELECT USING ( 
    auth.uid() = user_id OR (user_email IS NOT NULL AND (auth.jwt() ->> 'email') = user_email)
);

DROP POLICY IF EXISTS "Admins can do everything on bookings" ON public.bookings;
CREATE POLICY "Admins can do everything on bookings" ON public.bookings FOR ALL USING ( 
    EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

-- Reset Policies Properties
DROP POLICY IF EXISTS "Public properties are viewable by everyone" ON public.properties;
CREATE POLICY "Public properties are viewable by everyone" ON public.properties FOR SELECT USING (true);

-- Reset Policies Profiles
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

COMMIT;
