-- FASE 1: Database & Auth Setup (CORRETTO & ROBUSTO)

-- 1. PREPARAZIONE PROFILI & RUOLI
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  role text default 'user' check (role in ('user', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;

-- Policies (Drop preventivo per evitare errori "already exists")
drop policy if exists "Public profiles are viewable by everyone." on public.profiles;
create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

drop policy if exists "Users can update own profile." on public.profiles;
create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- Funzione e Trigger per nuovi utenti
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'user');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger: se non esiste, crealo (il replace function è safe, il trigger va droppato prima)
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. AGGIORNAMENTO TABELLA PROPERTIES (Per supportare il frontend)
-- Assicuriamoci che la tabella properties esista e abbia le colonne JSON necessarie
create table if not exists public.properties (
    id bigint primary key, 
    title text not null,
    description text,
    price decimal(10, 2),
    city text,
    address text,
    lat double precision,
    lng double precision,
    bedrooms int,
    bathrooms int,
    guests int,
    area int,
    image_url text, -- Immagine principale
    
    -- Colonne JSON per dettagli avanzati (richieste da page.tsx)
    specs jsonb default '{}'::jsonb,        -- Per technical_specs
    features jsonb default '[]'::jsonb,     -- Per features list
    images jsonb default '[]'::jsonb,       -- Per galleria
    extra_options jsonb default '[]'::jsonb, -- Per opzioni extra
    
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Se la tabella esisteva già, aggiungiamo le colonne mancanti
alter table public.properties add column if not exists specs jsonb default '{}'::jsonb;
alter table public.properties add column if not exists features jsonb default '[]'::jsonb;
alter table public.properties add column if not exists images jsonb default '[]'::jsonb;
alter table public.properties add column if not exists extra_options jsonb default '[]'::jsonb;

alter table public.properties enable row level security;

drop policy if exists "Public properties are viewable by everyone" on public.properties;
create policy "Public properties are viewable by everyone" 
  on public.properties for select 
  using (true);

-- 3. TABELLA PRENOTAZIONI (BOOKINGS)
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id),
  
  user_email text not null,
  user_id uuid references auth.users(id),
  
  start_date date not null,
  end_date date not null,
  
  total_price decimal(10, 2) not null default 0,
  
  status text default 'pending' check (status in ('pending', 'confirmed', 'paid', 'cancelled')),
  
  extra_services jsonb default '[]'::jsonb,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.bookings enable row level security;

-- Policies Bookings
drop policy if exists "Anyone can create a booking" on public.bookings;
create policy "Anyone can create a booking" 
  on public.bookings for insert 
  with check (true);

drop policy if exists "Users can view own bookings" on public.bookings;
create policy "Users can view own bookings"
  on public.bookings for select
  using ( 
    auth.uid() = user_id 
    OR 
    (auth.jwt() ->> 'email') = user_email 
  );

drop policy if exists "Admins can do everything on bookings" on public.bookings;
create policy "Admins can do everything on bookings"
  on public.bookings for all
  using ( 
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );
